# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Magnus Sundström
email: contact@magnussundstrom.se
description: >- # this means to ignore newlines until "baseurl:"
  Software developer and consultant based in Stockholm, Sweden. Currently employed at One Agency AB. Blogging about dev life in general, .NET development in particular.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lordpansar
github_username:  lordpansar
linkedin_username: kmvsundstrom

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-target-blank
future: false

  
# General settings
site.show_excerpts: true
page.author: Magnus Sundström

# Global variables
site.url: https://magnussundstrom.se
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
